### ISSUE TITLE
Ajustements visuels sur stock

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellihealth-web#18]
Les modifications décrites dans l’image jointe amélioreront l’ergonomie de cette page
![Image](https://i.imgur.com/1EIH3Sa.jpg)

**Comment by savioarthu** [comment]
Tout est ok !
<img width="1365" alt="Mesures" src="https://user-images.githubusercontent.com/49641714/68757760-c7d1a180-060c-11ea-9923-c10dd77a10aa.png">
