### ISSUE TITLE
#MelliCharts : Mesures

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellihealth-web#25]
a. Première chose, le temps de latence est très long sur cette page, que j’ai 5 mois de données à charger ou 3 jours. On a même l’impression que le temps de latence ne change pas lorsque la période est plus grande ou plus courte. 

b. Les bandes grises/blanches ne signifient absolument rien et ont tendance à troubler l’utilisateur. Impossible de les fixer en fonction de la période choisie ? Exemple : 1 jour pour une période de 7 jours, 1 semaine pour une période d’un mois, 1 mois pour une période de 6 mois ? etc.
Peut-être la possibilité de fonctionner avec un switch ? Si période = 7 jours : couper en 7; si période = 3 jours: couper en 3; si période = 15 jours : couper en 3;  etc. 

<img width="1364" alt="Capture d’écran 2019-11-07 à 09 15 38" src="https://user-images.githubusercontent.com/49641714/68371874-f00a5d80-013f-11ea-8e66-880fcdd18258.png">

c. Les axes n’ont pas toujours le même axe d’origine des dates. Il faut donc régler l’axe pour tout le monde à la même échelle. Pour remédier au problème, il suffit de prendre l’axe de la données la plus récente et fixer l’axe pour les 2 autres graphiques.

<img width="1352" alt="Fixer axes" src="https://user-images.githubusercontent.com/49641714/68371491-15e33280-013f-11ea-83c0-d5ced476084c.png">

**Comment by lzpons** [comment]
concernant les bandes grisées, j'ai écrit quelques guidelines sur SPEC_#SP19_Mellisphera_v2.ppt page 27. Ceci est un improvement. à dissocier du bug décrit par @savioarthu ci dessus.


![image](https://user-images.githubusercontent.com/41069288/68525766-4a88f280-02d5-11ea-9cf6-34fe46d02830.png)
