### ISSUE TITLE
#MelliCharts : Affichage date du jour

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellihealth-web#27]
Problème date du jour calendrier.
a. Un coin rouge s’affiche au milieu de la page lorsqu’on modifie la date à une date antérieure à celle du jour. Suffit de mettre une condition je pense, quand date du jour pas sélectionnée alors ne pas afficher carré rouge. 

<img width="113" alt="Coin rouge" src="https://user-images.githubusercontent.com/49641714/68372108-83dc2980-0140-11ea-97e3-da43ab0e5af2.png">

b. D’ailleurs, il faudrait rajouter cette case rouge pour le premier calendrier également.

<img width="1299" alt="Calendriers" src="https://user-images.githubusercontent.com/49641714/68372469-357b5a80-0141-11ea-8a08-d88d7e476eaf.png">

c. Quand je vais dans le futur, cette case rouge saute pour le calendrier de droite

<img width="374" alt="Disparu" src="https://user-images.githubusercontent.com/49641714/68372602-812e0400-0141-11ea-9e3b-3afe186677f6.png">

**Comment by lzpons** [comment]
@mickael2407 si possible réduis la taille du cadre rouge pour qu'il soit à l’intérieur de la cellule et non par dessus comme actuellement. 
de la même manière change lui la couleur rouge (pas bien connoté et en plus fait partie du color-map) par une couleur violette qui ne se confondra pas.

voici un exemple de la cible :
![Capture d’écran 2019-11-09 à 09 36 20](https://user-images.githubusercontent.com/41069288/68525703-a0a96600-02d4-11ea-9cb2-c22ecfb67799.png)

**Comment by savioarthu** [comment]
Ok pour la taille du cadre pour qu'il soit à l'intérieur de la case et quand je vais dans le futur ça fonctionne. Il reste 2/3 choses à régler :
1) Quand je me rend au jour précèdent, la case reste.
<img width="352" alt="Jour précédent" src="https://user-images.githubusercontent.com/49641714/68755230-71fafa80-0608-11ea-906b-129a7c3fe0f5.png">
2) Quand je vais à une date antérieure sans que la date du jour soit compris, par exemple avec la flèche, le cadre rouge se dérobe.
<img width="577" alt="Bug case" src="https://user-images.githubusercontent.com/49641714/68755335-a2429900-0608-11ea-80e1-e1930bae10e1.png">
3) Le dernier calendrier ne possède pas sa case
<img width="415" alt="Pas de case" src="https://user-images.githubusercontent.com/49641714/68755431-c605df00-0608-11ea-8aa0-2e5f4ec56289.png">

4) Il faut changer la couleur du rouge au violet (cf message Lorenzo au dessus)

**Comment by savioarthu** [comment]
Tout fonctionne, ne reste plus qu'à passer la case en violet (cf lorenzo)

**Comment by savioarthu** [comment]
Ok c'est parfait ! 
<img width="1335" alt="Purple" src="https://user-images.githubusercontent.com/49641714/68866338-87e5e980-06f4-11ea-82c0-e86324cfa96e.png">
