### ISSUE TITLE
#MelliUx : Affichages

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellihealth-web#32]
1) Quand je veux modifier une action, on ne voit pas le bouton.
<img width="382" alt="Modifier Notes" src="https://user-images.githubusercontent.com/49641714/68377711-30230d80-014b-11ea-95ff-8bbaf07c9663.png">

2) Mettre les + en vert pour être en cohérence totale dans tout le site

<img width="131" alt="Couleur +" src="https://user-images.githubusercontent.com/49641714/68377774-46c96480-014b-11ea-81f8-60370143b10d.png">

3) Impossible d’enlever les numéros des alertes
Système : Quand je clique sur une ruche avec une pastille d'alertes, la pastille s'efface.

**Comment by lzpons** [comment]
Hello Mickael,

une bonne pratique pour la fermeture des issues est de détailler les modifications apportées.
dans ce cas t’aurais pu mettre une capture d’écran de la nouvelle interface.

On apprend à s’en servir, mais je suis convaincu qu’on y gagnera en qualité !

A+
Lorenzo

Le 7 nov. 2019 à 15:25, mickael.pezzoni <notifications@github.com<mailto:notifications@github.com>> a écrit :


Closed #32<https://github.com/mellisphera/mellihealth-web/issues/32>.
