### ISSUE TITLE
Mise à jour du lien Slack

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellihealth-web#38]
Le lien Stack n'est plus fonctionnel, il faut le mettre à jour.
@lzpons connaît la procédure et doit fournir le nouveau lien à @mickael2407 pour qu'il modifie le lien sur le web. 

<img width="589" alt="Contact" src="https://user-images.githubusercontent.com/49641714/68383319-ba706f00-0155-11ea-8a2e-b78201893f07.png">

<img width="584" alt="Lien invalide" src="https://user-images.githubusercontent.com/49641714/68383320-ba706f00-0155-11ea-8973-53061ed2486e.png">

**Comment by lzpons** [comment]
liens envoyés par email. 
un lien permanent pour s'inscrire (confidentiel = à mettre dans les paramètres d'environnement)
et les deux liens d'accès direct vers les canaux mellisphera FR et EN comme ceux-ci
- https://mellisphera.slack.com/messages/mellisphera_fr/
- https://mellisphera.slack.com/messages/mellisphera_en/

J'ai mis à jour le guide 19 pour tracer la manière d'obtenir ces infos

**Comment by savioarthu** [comment]
Tout fonctionne :) 
<img width="526" alt="Connexion" src="https://user-images.githubusercontent.com/49641714/68690878-0d419080-0573-11ea-9d72-3e84f2eaf006.png">
<img width="591" alt="Rejoindre" src="https://user-images.githubusercontent.com/49641714/68690889-14689e80-0573-11ea-86c0-f6905cbc1c96.png">
<img width="291" alt="Message Slack EN" src="https://user-images.githubusercontent.com/49641714/68690905-1df20680-0573-11ea-913a-393e08f439f0.png">

<img width="291" alt="Message Slack FR" src="https://user-images.githubusercontent.com/49641714/68690905-1df20680-0573-11ea-913a-393e08f439f0.png">
