### ISSUE TITLE
changer le picto des alertes

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellihealth-web#40]
Au lieu des trois roues crantées, mettre un picto notifications (clochette) pour identifier l'écran de configuration des notifs.

Ce picto se trouve dans pictos/notifs sur github
il va peut être falloir le retoucher pour qu'il ressemble aux autres (fond blanc, épaisseur et couleur de trait)
![notif](https://user-images.githubusercontent.com/41069288/68418845-5f606b80-0199-11ea-8e64-4cb981fa7812.png)

**Comment by savioarthu** [comment]
Ok, on a mis à jour le picto, tu iras voir quand ça sera déployé et tu nous diras si ça te convient

**Comment by lzpons** [comment]
👍😍

Le 8 nov. 2019 à 15:11, Arthur Savio <notifications@github.com<mailto:notifications@github.com>> a écrit :


Ok, on a mis à jour le picto, tu iras voir quand ça sera déployé et tu nous diras si ça te convient
