### ISSUE TITLE
la pastille de couvain est toujours blanche sur les navigateurs US

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellihealth-web#41]
Pour une raison qu'on ignore la couleur de la pastille de couvain apparait vide sur le browser de Rich. Alors que sur un browser EU ça marche (voir image)

Solution envisageable :
- Vérifier si c'est le cas pour d'autres utilisateurs US
- contrôler également les autres champs (météo par exemple)
- il se peut que ce soit lié aux paramètres du browser?

![Capture d’écran 2019-11-07 à 23 13 14](https://user-images.githubusercontent.com/41069288/68432532-ebcc5780-01b4-11ea-84c2-d0c3f3074574.png)

De façon semblable les notes sur le calendrier des evennements ne se chargent jamais sur son navigateur (toujours loading), alors que sur le mien ça passe sans soucis.

![Capture d’écran 2019-11-07 à 23 05 22](https://user-images.githubusercontent.com/41069288/68432836-84fb6e00-01b5-11ea-8f5e-9ac588c116fa.png)

**Comment by mickael2407** [comment]
Sans plus d'information (il me faudrait les erreurs console) impossible de savoir j'ai essayé en passants par des proxy pour avoir des ip us et ça fonctionne donc mystère .

**Comment by savioarthu** [comment]
Je leur demande plus de précisions sur Slack.
