### ISSUE TITLE
création de notes de type "action" produit un texte vide

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellihealth-web#43]
Description :
Lorsqu'on crée une note de type action le texte n'est pas enregistré et la note apparait vide.
ensuite on peut l'éditer mais il faut tout saisir.

Objectif :
on va supprimer la notion action/observation et garder uniquement "creer note" sans faire la distinction. 
Faire évoluer l'interface en ce sens pour simplifier la saisie.
![Capture d’écran 2019-11-10 à 12 58 15](https://user-images.githubusercontent.com/41069288/68543644-24894e00-03ba-11ea-8f2f-7ccbaf1e760d.png)

**Comment by savioarthu** [comment]
Toujours la possibilité de créer une observation ou une action pour les ruches.
<img width="588" alt="Capture d’écran 2019-11-13 à 11 17 23" src="https://user-images.githubusercontent.com/49641714/68754572-3d3a7380-0607-11ea-98d1-06b528bd9b97.png">

**Comment by savioarthu** [comment]
Ok, par contre, une fois que la note est créée, on peut toujours choisir une observation et une action. 
<img width="588" alt="Choix Observation/Action" src="https://user-images.githubusercontent.com/49641714/68846962-23179880-06ce-11ea-9e5a-5c457d7326bb.png">

Et autre détail, quand je modifie une note et que je ferme le menu, deux possibilités:
-Si c'est une observation, le bouton devient bleu
<img width="69" alt="Bleu" src="https://user-images.githubusercontent.com/49641714/68847104-607c2600-06ce-11ea-83bc-cf3b4043347c.png">

-Si c'est une action il devient transparent/invisible
<img width="61" alt="Blanc" src="https://user-images.githubusercontent.com/49641714/68847116-67a33400-06ce-11ea-9b43-880deba63cf8.png">
